name: Game in a frame
favicon: null
layout_spectrum: 0.9568847587797791
typography_spectrum: 0.1203993116505444
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.18700753268785775
  lightness: 0.019886520924046636
  saturation: 0.3596334923058748
  rhythmicContrast: 0.3261019529309124
purpose: []
