typography_spectrum: 0.09993
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.125
  lightness: 0.019886520924046636
  saturation: 0.5
  rhythmicContrast: 0.3261019529309124
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.26212
analytics:
  google: null
  facebook: null
  twitter: null
name: Game in a frame
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Gaming nostalgia
purpose: []
